AWSTemplateFormatVersion: 2010-09-09
Description: Risk Prediction Model

Parameters: 
  StackName:
    Type: String
  InstanceType:
    Description: Instance type
    Type: String
    Default: ml.m4.xlarge
  InstanceCount:
    Description: Instance count
    Type: String
    Default: 1

Mappings:
  RegionMap:
    "us-west-2":
      "Container": "246618743249.dkr.ecr.us-west-2.amazonaws.com/sagemaker-xgboost:1.0-1-cpu-py3"
    "us-east-1":
      "Container": "683313688378.dkr.ecr.us-east-1.amazonaws.com/sagemaker-xgboost:1.0-1-cpu-py3"
    "us-east-2":
      "Container": "257758044811.dkr.ecr.us-east-2.amazonaws.com/sagemaker-xgboost:1.0-1-cpu-py3"
    "us-west-1":
      "Container": "746614075791.dkr.ecr.us-west-1.amazonaws.com/sagemaker-xgboost:1.0-1-cpu-py3"                   
    "ap-northeast-1":
      "Container": "354813040037.dkr.ecr.ap-northeast-1.amazonaws.com/sagemaker-xgboost:1.0-1-cpu-py3"
    "ap-northeast-2":
      "Container": "366743142698.dkr.ecr.ap-northeast-2.amazonaws.com/sagemaker-xgboost:1.0-1-cpu-py3"
    "ap-southeast-1":
      "Container": "121021644041.dkr.ecr.ap-southeast-1.amazonaws.com/sagemaker-xgboost:1.0-1-cpu-py3"
    "ap-southeast-2":
      "Container": "783357654285.dkr.ecr.ap-southeast-2.amazonaws.com/sagemaker-xgboost:1.0-1-cpu-py3"
    "ap-south-1":
      "Container": "720646828776.dkr.ecr.ap-south-1.amazonaws.com/sagemaker-xgboost:1.0-1-cpu-py3"
    "ap-east-1":
      "Container": "651117190479.dkr.ecr.ap-east-1.amazonaws.com/sagemaker-xgboost:1.0-1-cpu-py3"
    "ca-central-1":
      "Container": "341280168497.dkr.ecr.ca-central-1.amazonaws.com/sagemaker-xgboost:1.0-1-cpu-py3"
    "cn-north-1":
      "Container": "450853457545.dkr.ecr.cn-north-1.amazonaws.com.cn/sagemaker-xgboost:1.0-1-cpu-py3"
    "cn-northwest-1":
      "Container": "451049120500.dkr.ecr.cn-northwest-1.amazonaws.com.cn/sagemaker-xgboost:1.0-1-cpu-py3"
    "eu-central-1":
      "Container": "492215442770.dkr.ecr.eu-central-1.amazonaws.com/sagemaker-xgboost:1.0-1-cpu-py3"
    "eu-north-1":
      "Container": "662702820516.dkr.ecr.eu-north-1.amazonaws.com/sagemaker-xgboost:1.0-1-cpu-py3"
    "eu-west-1":
      "Container": "141502667606.dkr.ecr.eu-west-1.amazonaws.com/sagemaker-xgboost:1.0-1-cpu-py3"
    "eu-west-2":
      "Container": "764974769150.dkr.ecr.eu-west-2.amazonaws.com/sagemaker-xgboost:1.0-1-cpu-py3"
    "eu-west-3":
      "Container": "659782779980.dkr.ecr.eu-west-3.amazonaws.com/sagemaker-xgboost:1.0-1-cpu-py3"
    "me-south-1":
      "Container": "801668240914.dkr.ecr.me-south-1.amazonaws.com/sagemaker-xgboost:1.0-1-cpu-py3"
    "sa-east-1":
      "Container": "737474898029.dkr.ecr.sa-east-1.amazonaws.com/sagemaker-xgboost:1.0-1-cpu-py3"
      
Resources:

  SagemakerModelRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SagemakerModelPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub "arn:aws:s3:::*"

  Model:
    Type: "AWS::SageMaker::Model"
    Properties:
      Containers:
        -
          Image: !FindInMap [RegionMap, !Ref "AWS::Region", "Container"]
          ModelDataUrl: !Sub "s3://${StackName}/output/model/model-33cf1420.tar.gz"
      ExecutionRoleArn: !GetAtt SagemakerModelRole.Arn
      ModelName: !Sub "${StackName}-model"

  Endpoint:
    Type: "AWS::SageMaker::Endpoint"
    Properties:
      EndpointConfigName: !GetAtt EndpointConfig.EndpointConfigName
      EndpointName: !Sub "${StackName}-ep"

  EndpointConfig:
    Type: "AWS::SageMaker::EndpointConfig"
    Properties:
      ProductionVariants:
        -
          ModelName: !GetAtt Model.ModelName
          VariantName: variant-1
          InitialInstanceCount: !Ref InstanceCount
          InstanceType: !Ref InstanceType
          InitialVariantWeight: 1.0
      EndpointConfigName: !Sub "${StackName}-epc"

Outputs:
  EndpointId:
    Value: !Ref Endpoint
  EndpointName:
    Value: !GetAtt Endpoint.EndpointName

